# -*- coding: utf-8 -*-
"""Web scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1z2BZvWHlGuF6t6glH12g_DcvpYv_XT
"""

!pip install lxml[html_clean]
!pip install -q python-mecab-ko
!pip install -q tqdm
!pip install newspaper3k
!pip install trafilatura

import warnings
warnings.filterwarnings('ignore')

import os
import re
import glob
import pandas as pd
from tqdm import tqdm
from mecab import MeCab
from newspaper import Article
import time
from google.colab import files
from google.colab import drive
import requests
import trafilatura
from urllib.parse import urlparse

drive.mount('/content/drive')

path = '/content/drive/MyDrive/data'

data_file list = glob.glob(path + '/*.xlsx')

df = pd.DataFrame()

for file in file_list:
    df2 = pd.read_excel(file)
    df = pd.concat([df, df2], ignore_index=True)

print(f"Total files loaded: {len(file_list)}")
print("Data sample:")
print(df.head())
print("\nDataset summary:")
df.info()

df["키워드"].value_counts() # "키워드" - keyword

df['URL'].tail()

url_list = df['URL'].tolist()

print(f"Total URLs to crawl: {len(url_list)}")

scraped_texts = []
for url in tqdm(url_list, desc="Progress"):
    try:
        article = Article(url, language='ko')
        article.download()
        article.parse()
        scraped_texts.append(article.text)
        print(f"[OK] {url[:70]}...")
    except Exception as e:
        scraped_texts.append(None)
        print(f"[ERROR] {url[:70]}... | {e}")

    time.sleep(0.1)

df['content'] = scraped_texts

missing_by_year = df[df[content_col].isna() | (df[content_col].astype(str).str.strip() == '')].groupby('year').size()

if missing_by_year.empty:
    print("No missing content detected.")
else:
    print("Missing content by year:")
    print(missing_by_year)

def is_null(x):
    if pd.isna(x): return True
    s = str(x).strip()
    return len(s) < 10 or s.lower() in ['nan', 'none', '']

def fix_url(u):
    if pd.isna(u): return None
    u = str(u).strip()
    if not u.startswith('http'):
        u = 'https:' + u if u.startswith('//') else 'https://' + u
    return u

def get_text(url, timeout=10):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        resp = requests.get(url, timeout=timeout, headers=headers, allow_redirects=True)
        txt = extract_by_domain(url, resp.text)

        if not txt or len(txt) < 200:
            downloaded = trafilatura.fetch_url(url)
            txt = trafilatura.extract(downloaded)
        return txt.strip() if txt else None
    except:
        return None

mask = df["content"].apply(is_null)
df.loc[mask, "URL"] = df.loc[mask, "URL"].apply(fix_url)

targets = df[mask].copy()
targets = targets[targets["URL"].str.startswith('http', na=False)]

print(f"Missing rows: {len(targets)} / Total: {len(df)}")

ok_list, fail_list = [], []
cache = {}

for idx, row in tqdm(targets.iterrows(), total=len(targets), desc="Crawling"):
    url = row["URL"]

    if url in cache:
        txt = cache[url]
    else:
        txt = get_text(url)
        cache[url] = txt

    if txt and len(txt) >= 200:
        df.at[idx, "content"] = txt
        ok_list.append({"idx": idx, "url": url, "content": txt})
    else:
        fail_list.append({"idx": idx, "url": url})

    time.sleep(0.1)

print(f"\nFinished! Success: {len(ok_list)}, Fail: {len(fail_list)}")

print(f"After recovery, missing content: {(df['content'].isna()).sum()}")
import os

output_dir = "./yearly_csv"
os.makedirs(output_dir, exist_ok=True)

for year, df_year in df.groupby('year'):
    output_path = os.path.join(output_dir, f"data_{year}.csv")
    df_year.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {output_path} ({len(df_year)} rows)")
